### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by nmezzopera** [vue-leaflet/vue2-leaflet-polylineoffset#1]
@maratumba Thank you so much for bringing the repository in the org. Do you have all the right permissions? Is anything that we could do better?

I am planning on creating a repo as a 'template' for new plugins, with:

- folder structure
- tests
- example file where to drop in the code
- instructions

**Comment by maratumba** [comment]
Good to be here! I created a repo and pushed the plugin so I think I have all the necessary permissions. I was hesitant about the naming of the plugin (`VueLeaflet-polylineoffset`? `vue2-leaflet-polylineoffset`?) so if you want to change it in the future, that's ok by me.

Testing would be a really good addition. Looking forward to your template.

**Comment by nmezzopera** [comment]
@maratumba I think the name is good as it is! Question would you like to release the npm package as part of the organization or you would prefer to do so on your own name? both are fine!

**Comment by maratumba** [comment]
I think I'd prefer it to keep it under my account for now. It's my only npm package :)

**Comment by maratumba** [comment]
@DonNicoJs, any chance to add this to the vue-leaflet plugins list?
