### ISSUE TITLE
offset line in some times inside some time outside

### ISSUE THREAD

**Issue by farhad-rohani** [vue-leaflet/vue2-leaflet-polylineoffset#2]
hello 
tanck you for create this plugin

When we swipe to the right, the offset line (white) is at the top, 
![image](https://user-images.githubusercontent.com/9474884/126889761-5bdb6156-9628-4544-89cb-bacb7dbb66c7.png)
![image](https://user-images.githubusercontent.com/9474884/126889797-4d6c1af9-2a53-4301-a77c-799a98a3bc86.png)

and when we swipe to the left, the offset line (white)  is at the bottom.
![image](https://user-images.githubusercontent.com/9474884/126889803-56b9215e-ecc7-4b59-a822-47d30ddbbe36.png)
![image](https://user-images.githubusercontent.com/9474884/126889813-810d2669-5842-4d05-bf94-1f917ea78954.png)

This becomes a problem when we want to make a polygon. One of the corners of the polygon breaks.
![image](https://user-images.githubusercontent.com/9474884/126889920-7fd3675b-2fa4-41d3-8bd1-9e3b5171b209.png)

left-botton or right-top offset line (white) is outside
![image](https://user-images.githubusercontent.com/9474884/126889828-3d5852d3-450e-466f-a906-a8d88b6da6e3.png)

left-top or right-botton offset line (white) is inside
![image](https://user-images.githubusercontent.com/9474884/126889863-51562001-e2ea-4b27-bbe4-c654201a701b.png)

**Comment by maratumba** [comment]
Thank you for your report. My plugin is just a wrapper around the [leaflet offset line plugin](https://github.com/bbecquet/Leaflet.PolylineOffset), I would suggest to bring up the issue there. 

My suggestion would be to make sure that the order of points always follows a Clock-wise or counter clock-wise direction in closed polygons. As the offset is given relative to the direction of the lines, you have to manually check the line array and invert if necessary.
